### ISSUE TITLE
Issues of Porting the cage-tool Project to Ubuntu

### ISSUE THREAD

**Issue by 271806** [TexelBox/cage-tool#1]
# Issues of Porting the cage-tool Project to Ubuntu

I am encountering an issue while porting the cage-tool project from Windows to Ubuntu 22.04. The project was originally built for Windows, but I'm trying to run it on Ubuntu. I have made some modifications to the CMakeLists.txt file and fixed some build errors, but the program is still crashing shortly after startup.

## Problem Description
- The program compiles successfully using CMake and Make on Ubuntu 22.04.
- However, when running the executable, a window appears briefly and then closes immediately.
- The program seems to be crashing during the initialization of the `RenderEngine` object, specifically when compiling shaders using the `ShaderTools::compileShaders` function.

## Debugging Attempts
1. I used GDB to debug the program and set a breakpoint at the `RenderEngine` constructor.
2. Stepping through the code, I observed that the program enters the `ShaderTools::compileShaders` function and starts loading the shader source files.
3. The vertex shader and fragment shader source files are loaded correctly using the `loadshader` function.
4. However, the program crashes with a segmentation fault inside the `__strlen_avx2` function, which is a low-level string length function optimized for AVX2 instructions.

CMakeLists.txt
```
# Set the minimum required version
cmake_minimum_required(VERSION 3.22)

# Define project name and specify the languages used
project(CageTool LANGUAGES CXX)

# Specify the C++ standard
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# List the source files for ImGui
set(IMGUI_SOURCES
    include/imgui/imgui.cpp
    include/imgui/imgui_demo.cpp
    include/imgui/imgui_draw.cpp
    include/imgui/imgui_widgets.cpp
    include/imgui/imgui_impl_glfw.cpp
    include/imgui/imgui_impl_opengl3.cpp
)

# Create a static library for ImGui
add_library(ImGui STATIC ${IMGUI_SOURCES})
target_include_directories(ImGui PUBLIC 
    ${CMAKE_CURRENT_SOURCE_DIR}/include/imgui
)

# Find packages
find_package(OpenGL REQUIRED)
find_package(GLEW REQUIRED)
find_package(glfw3 REQUIRED)

# Explicitly set OpenGL preference (new policy in CMake 3.11 and later)
set(OpenGL_GL_PREFERENCE GLVND)

# List source files
set(SOURCES
    src/main.cpp
    src/Camera.cpp
    src/InputHandler.cpp
    src/lodepng.cpp
    src/MeshObject.cpp
    src/ObjectLoader.cpp
    src/Program.cpp
    src/RenderEngine.cpp
    src/ShaderTools.cpp
    src/Texture.cpp
)

# Define project's executable
add_executable(${PROJECT_NAME} ${SOURCES})

# Link project with required libraries
target_link_libraries(${PROJECT_NAME} 
    OpenGL::GL
    GLEW::GLEW
    glfw
    ImGui
)

# Include directories
target_include_directories(${PROJECT_NAME} PUBLIC 
    ${CMAKE_CURRENT_SOURCE_DIR}/include
    ${CMAKE_CURRENT_SOURCE_DIR}/include/GLFW
    ${CMAKE_CURRENT_SOURCE_DIR}/include/glm
)
```

## Relevant Code
- `RenderEngine` constructor in `RenderEngine.cpp`:
```cpp
RenderEngine::RenderEngine(GLFWwindow *window, std::shared_ptr<Camera> camera) : window(window), camera(camera) {
    // ...
    trivialProgram = ShaderTools::compileShaders("shaders/trivial.vert", "shaders/trivial.frag");
    mainProgram = ShaderTools::compileShaders("shaders/main.vert", "shaders/main.frag");
    lightProgram = ShaderTools::compileShaders("shaders/light.vert", "shaders/light.frag");
    pickingProgram = ShaderTools::compileShaders("shaders/picking.vert", "shaders/picking.frag");
    // ...
}
```

- `ShaderTools::compileShaders` function in `ShaderTools.cpp`:

```cpp
GLuint ShaderTools::compileShaders(const char* vertexFilename, const char* fragmentFilename) {
    // ...
    const GLchar * vertex_shader_source [] = {loadshader(vertexFilename)};
    const GLchar * fragment_shader_source [] = {loadshader(fragmentFilename)};
    // ...
}
```

- GDB Backtrace
```cpp
Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) backtrace
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007ffff4d3998c in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.535.161.07
#2  0x00007ffff4d39f14 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.535.161.07
#3  0x00005555555b7435 in ShaderTools::compileShaders(char const*, char const*) ()
#4  0x00005555555b5763 in RenderEngine::RenderEngine(GLFWwindow*, std::shared_ptr<Camera>) ()
...
```

## Possible Causes
- The crash could be related to differences in how the shader files are handled or how the OpenGL context is set up on Ubuntu compared to Windows.
- There might be platform-specific assumptions or dependencies in the code that are not met on Ubuntu.
- The issue could be related to shader compilation or loading, as the crash occurs during the shader compilation process.
I have tried adding more error checking and logging statements in the shader compilation code, but the exact cause of the crash remains unclear.

Any suggestions or insights on how to resolve this issue and successfully port the cage-tool project to Ubuntu would be greatly appreciated. Please let me know if you need any additional information or code snippets to further investigate the problem.

**Comment by 271806** [comment]
After trying to figure out the cause of the error with my colleague, I have a preliminary view of this issue, which I'm trying to resolve, though more discussion and suggestions are still welcome!
